name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PS2EXE
      run: Install-Module -Name PS2EXE -Scope CurrentUser -Force
      shell: powershell

    - name: Compile Executable
      run: |
        ps2exe -inputFile "qBitLauncher.ps1" -outputFile "qBitLauncher.exe" -iconFile "qBitLauncher Logo.ico" -noConsole
      shell: powershell

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qBitLauncher.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
